// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhdywmlyubwepsvrsvvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoZHl3bWx5dWJ3ZXBzdnJzdnZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MjQ2MDMsImV4cCI6MjA3MzIwMDYwM30.1gRISBOdyGvl456dxxeUp0ZT6sX2MQDW7H84g0ok3CM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});